[package]
name = "polylog"
version = "0.2.1"
authors = ["Alexander Voigt <Alexander.Voigt@physik.rwth-aachen.de>"]
license = "LGPL-3.0-only"
readme = "README.md"
description = "Rust implementation of polylogarithms."
homepage = "https://github.com/Expander/polylog"
repository = "https://github.com/Expander/polylog"

[dependencies]
num = "0.1"
rand = "0.5.5"
